/********************************************************************
* MyDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error MyDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableMyDict();
extern void G__cpp_setup_inheritanceMyDict();
extern void G__cpp_setup_typetableMyDict();
extern void G__cpp_setup_memvarMyDict();
extern void G__cpp_setup_globalMyDict();
extern void G__cpp_setup_memfuncMyDict();
extern void G__cpp_setup_funcMyDict();
extern void G__set_cpp_environmentMyDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "include/TCalibrate.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__MyDictLN_TClass;
extern G__linked_taginfo G__MyDictLN_TBuffer;
extern G__linked_taginfo G__MyDictLN_TMemberInspector;
extern G__linked_taginfo G__MyDictLN_TObject;
extern G__linked_taginfo G__MyDictLN_TNamed;
extern G__linked_taginfo G__MyDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__MyDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__MyDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__MyDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__MyDictLN_TCalibrate;

/* STUB derived class for protected member access */
