/********************************************************************
* TObjectManagerDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error TObjectManagerDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableTObjectManagerDict();
extern void G__cpp_setup_inheritanceTObjectManagerDict();
extern void G__cpp_setup_typetableTObjectManagerDict();
extern void G__cpp_setup_memvarTObjectManagerDict();
extern void G__cpp_setup_globalTObjectManagerDict();
extern void G__cpp_setup_memfuncTObjectManagerDict();
extern void G__cpp_setup_funcTObjectManagerDict();
extern void G__set_cpp_environmentTObjectManagerDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "/home/tiguser/packages/SharcCalibration/include/TObjectManager.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__TObjectManagerDictLN_TClass;
extern G__linked_taginfo G__TObjectManagerDictLN_TBuffer;
extern G__linked_taginfo G__TObjectManagerDictLN_TMemberInspector;
extern G__linked_taginfo G__TObjectManagerDictLN_TObject;
extern G__linked_taginfo G__TObjectManagerDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__TObjectManagerDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TObjectManagerDictLN_TList;
extern G__linked_taginfo G__TObjectManagerDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__TObjectManagerDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TObjectManagerDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__TObjectManagerDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__TObjectManagerDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__TObjectManagerDictLN_TObjectManager;

/* STUB derived class for protected member access */
