//
// File generated by rootcint at Fri Dec 12 15:49:04 2014

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME TObjectManagerDict
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "TObjectManagerDict.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TInterpreter.h"
#include "TVirtualMutex.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// Direct notice to TROOT of the dictionary's loading.
namespace {
   static struct DictInit {
      DictInit() {
         ROOT::RegisterModule();
      }
   } __TheDictionaryInitializer;
}

// START OF SHADOWS

namespace ROOT {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOT
// END OF SHADOWS

namespace ROOT {
   void TObjectManager_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void *new_TObjectManager(void *p = 0);
   static void *newArray_TObjectManager(Long_t size, void *p);
   static void delete_TObjectManager(void *p);
   static void deleteArray_TObjectManager(void *p);
   static void destruct_TObjectManager(void *p);
   static void streamer_TObjectManager(TBuffer &buf, void *obj);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::TObjectManager*)
   {
      ::TObjectManager *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::TObjectManager >(0);
      static ::ROOT::TGenericClassInfo 
         instance("TObjectManager", ::TObjectManager::Class_Version(), "/home/bender/Programs/SharcCalibration/include/TObjectManager.h", 11,
                  typeid(::TObjectManager), DefineBehavior(ptr, ptr),
                  &::TObjectManager::Dictionary, isa_proxy, 0,
                  sizeof(::TObjectManager) );
      instance.SetNew(&new_TObjectManager);
      instance.SetNewArray(&newArray_TObjectManager);
      instance.SetDelete(&delete_TObjectManager);
      instance.SetDeleteArray(&deleteArray_TObjectManager);
      instance.SetDestructor(&destruct_TObjectManager);
      instance.SetStreamerFunc(&streamer_TObjectManager);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::TObjectManager*)
   {
      return GenerateInitInstanceLocal((::TObjectManager*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::TObjectManager*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOT

//______________________________________________________________________________
atomic_TClass_ptr TObjectManager::fgIsA(0);  // static to hold class pointer

//______________________________________________________________________________
const char *TObjectManager::Class_Name()
{
   return "TObjectManager";
}

//______________________________________________________________________________
const char *TObjectManager::ImplFileName()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::TObjectManager*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int TObjectManager::ImplFileLine()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::TObjectManager*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void TObjectManager::Dictionary()
{
   fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::TObjectManager*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *TObjectManager::Class()
{
   if (!fgIsA) { R__LOCKGUARD2(gCINTMutex); if(!fgIsA) {fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::TObjectManager*)0x0)->GetClass();} }
   return fgIsA;
}

//______________________________________________________________________________
void TObjectManager::Streamer(TBuffer &R__b)
{
   // Stream an object of class TObjectManager.

   UInt_t R__s, R__c;
   if (R__b.IsReading()) {
      Version_t R__v = R__b.ReadVersion(&R__s, &R__c); if (R__v) { }
      TObject::Streamer(R__b);
      R__b >> fMasterList;
      R__b.CheckByteCount(R__s, R__c, TObjectManager::IsA());
   } else {
      R__c = R__b.WriteVersion(TObjectManager::IsA(), kTRUE);
      TObject::Streamer(R__b);
      R__b << fMasterList;
      R__b.SetByteCount(R__c, kTRUE);
   }
}

//______________________________________________________________________________
void TObjectManager::ShowMembers(TMemberInspector &R__insp)
{
      // Inspect the data members of an object of class TObjectManager.
      TClass *R__cl = ::TObjectManager::IsA();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fMasterList", &fMasterList);
      TObject::ShowMembers(R__insp);
}

namespace ROOT {
   // Wrappers around operator new
   static void *new_TObjectManager(void *p) {
      return  p ? new(p) ::TObjectManager : new ::TObjectManager;
   }
   static void *newArray_TObjectManager(Long_t nElements, void *p) {
      return p ? new(p) ::TObjectManager[nElements] : new ::TObjectManager[nElements];
   }
   // Wrapper around operator delete
   static void delete_TObjectManager(void *p) {
      delete ((::TObjectManager*)p);
   }
   static void deleteArray_TObjectManager(void *p) {
      delete [] ((::TObjectManager*)p);
   }
   static void destruct_TObjectManager(void *p) {
      typedef ::TObjectManager current_t;
      ((current_t*)p)->~current_t();
   }
   // Wrapper around a custom streamer member function.
   static void streamer_TObjectManager(TBuffer &buf, void *obj) {
      ((::TObjectManager*)obj)->::TObjectManager::Streamer(buf);
   }
} // end of namespace ROOT for class ::TObjectManager

/********************************************************
* TObjectManagerDict.cxx
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtableTObjectManagerDict();

extern "C" void G__set_cpp_environmentTObjectManagerDict() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("/home/bender/Programs/SharcCalibration/include/TObjectManager.h");
  G__cpp_reset_tagtableTObjectManagerDict();
}
#include <new>
extern "C" int G__cpp_dllrevTObjectManagerDict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* TObjectManager */
static int G__TObjectManagerDict_228_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   TObjectManager* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new TObjectManager[n];
     } else {
       p = new((void*) gvp) TObjectManager[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new TObjectManager;
     } else {
       p = new((void*) gvp) TObjectManager;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__TObjectManagerDictLN_TObjectManager));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TObjectManagerDict_228_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) TObjectManager::Get());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TObjectManagerDict_228_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 1:
      ((TObjectManager*) G__getstructoffset())->Print((Option_t*) G__int(libp->para[0]));
      G__setnull(result7);
      break;
   case 0:
      ((TObjectManager*) G__getstructoffset())->Print();
      G__setnull(result7);
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TObjectManagerDict_228_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TObjectManager*) G__getstructoffset())->AddObjectToList((TObject*) G__int(libp->para[0]), (const char*) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TObjectManagerDict_228_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 2:
      G__letint(result7, 85, (long) ((TObjectManager*) G__getstructoffset())->GetObject((const char*) G__int(libp->para[0]), (const char*) G__int(libp->para[1])));
      break;
   case 1:
      G__letint(result7, 85, (long) ((TObjectManager*) G__getstructoffset())->GetObject((const char*) G__int(libp->para[0])));
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TObjectManagerDict_228_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 2:
      G__letint(result7, 104, (long) ((TObjectManager*) G__getstructoffset())->CountObjectsOfType((const char*) G__int(libp->para[0]), (TList*) G__int(libp->para[1])));
      break;
   case 1:
      G__letint(result7, 104, (long) ((TObjectManager*) G__getstructoffset())->CountObjectsOfType((const char*) G__int(libp->para[0])));
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TObjectManagerDict_228_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ((TObjectManager*) G__getstructoffset())->GetList((const char*) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TObjectManagerDict_228_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ((TObjectManager*) G__getstructoffset())->GetMasterList());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TObjectManagerDict_228_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) TObjectManager::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TObjectManagerDict_228_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) TObjectManager::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TObjectManagerDict_228_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) TObjectManager::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TObjectManagerDict_228_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      TObjectManager::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TObjectManagerDict_228_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TObjectManager*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TObjectManagerDict_228_0_19(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) TObjectManager::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TObjectManagerDict_228_0_20(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) TObjectManager::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TObjectManagerDict_228_0_21(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) TObjectManager::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TObjectManagerDict_228_0_22(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) TObjectManager::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__TObjectManagerDict_228_0_23(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   TObjectManager* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new TObjectManager(*(TObjectManager*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__TObjectManagerDictLN_TObjectManager));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef TObjectManager G__TTObjectManager;
static int G__TObjectManagerDict_228_0_24(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (TObjectManager*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((TObjectManager*) (soff+(sizeof(TObjectManager)*i)))->~G__TTObjectManager();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (TObjectManager*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((TObjectManager*) (soff))->~G__TTObjectManager();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__TObjectManagerDict_228_0_25(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   TObjectManager* dest = (TObjectManager*) G__getstructoffset();
   *dest = *(TObjectManager*) libp->para[0].ref;
   const TObjectManager& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* TObjectManager */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncTObjectManagerDict {
 public:
  G__Sizep2memfuncTObjectManagerDict(): p(&G__Sizep2memfuncTObjectManagerDict::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncTObjectManagerDict::*p)();
};

size_t G__get_sizep2memfuncTObjectManagerDict()
{
  G__Sizep2memfuncTObjectManagerDict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceTObjectManagerDict() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__TObjectManagerDictLN_TObjectManager))) {
     TObjectManager *G__Lderived;
     G__Lderived=(TObjectManager*)0x1000;
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__TObjectManagerDictLN_TObjectManager),G__get_linked_tagnum(&G__TObjectManagerDictLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableTObjectManagerDict() {

   /* Setting up typedef entry */
   G__search_typename2("UInt_t",104,-1,0,-1);
   G__setnewtype(-1,"Unsigned integer 4 bytes (unsigned int)",0);
   G__search_typename2("Version_t",115,-1,0,-1);
   G__setnewtype(-1,"Class version identifier (short)",0);
   G__search_typename2("Option_t",99,-1,256,-1);
   G__setnewtype(-1,"Option string (const char)",0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__TObjectManagerDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__TObjectManagerDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__TObjectManagerDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__TObjectManagerDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__TObjectManagerDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__TObjectManagerDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__TObjectManagerDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__TObjectManagerDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__TObjectManagerDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__TObjectManagerDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<std::bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__TObjectManagerDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__TObjectManagerDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*>",117,G__get_linked_tagnum(&G__TObjectManagerDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long>",117,G__get_linked_tagnum(&G__TObjectManagerDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long,const TObject**>",117,G__get_linked_tagnum(&G__TObjectManagerDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Float_t>",117,G__get_linked_tagnum(&G__TObjectManagerDictLN_TVectorTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Double_t>",117,G__get_linked_tagnum(&G__TObjectManagerDictLN_TVectorTlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* TObjectManager */
static void G__setup_memvarTObjectManager(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__TObjectManagerDictLN_TObjectManager));
   { TObjectManager *p; p=(TObjectManager*)0x1000; if (p) { }
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__TObjectManagerDictLN_TObjectManager),-1,-2,4,"fObjectManager=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__TObjectManagerDictLN_TList),-1,-1,4,"fMasterList=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__TObjectManagerDictLN_TClass),G__defined_typename("atomic_TClass_ptr"),-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarTObjectManagerDict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncTObjectManager(void) {
   /* TObjectManager */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__TObjectManagerDictLN_TObjectManager));
   G__memfunc_setup("TObjectManager",1382,G__TObjectManagerDict_228_0_1, 105, G__get_linked_tagnum(&G__TObjectManagerDictLN_TObjectManager), -1, 0, 0, 1, 1, 0, "", "default  constructor.", (void*) NULL, 0);
   G__memfunc_setup("Get",288,G__TObjectManagerDict_228_0_2, 85, G__get_linked_tagnum(&G__TObjectManagerDictLN_TObjectManager), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TObjectManager* (*)())(&TObjectManager::Get) ), 0);
   G__memfunc_setup("Print",525,G__TObjectManagerDict_228_0_3, 121, -1, -1, 0, 1, 1, 1, 0, "C - 'Option_t' 10 '\"\"' opt", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Clear",487,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "C - 'Option_t' 10 '\"\"' opt", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("TObjectManager",1382,(G__InterfaceMethod) NULL, 105, G__get_linked_tagnum(&G__TObjectManagerDictLN_TObjectManager), -1, 0, 1, 1, 4, 0, "g - - 0 - -", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("AddObjectToList",1471,G__TObjectManagerDict_228_0_6, 121, -1, -1, 0, 2, 1, 1, 0, 
"U 'TObject' - 0 - object C - - 10 - listname", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetObject",887,G__TObjectManagerDict_228_0_7, 85, G__get_linked_tagnum(&G__TObjectManagerDictLN_TObject), -1, 0, 2, 1, 1, 0, 
"C - - 10 - oname C - - 10 '0' listname", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("CountObjectsOfType",1834,G__TObjectManagerDict_228_0_8, 104, -1, G__defined_typename("UInt_t"), 0, 2, 1, 1, 0, 
"C - - 10 - oname U 'TList' - 0 '0' list", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetList",700,G__TObjectManagerDict_228_0_9, 85, G__get_linked_tagnum(&G__TObjectManagerDictLN_TList), -1, 0, 1, 1, 1, 0, "C - - 10 - listname", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetMasterList",1320,G__TObjectManagerDict_228_0_10, 85, G__get_linked_tagnum(&G__TObjectManagerDictLN_TList), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Class",502,G__TObjectManagerDict_228_0_11, 85, G__get_linked_tagnum(&G__TObjectManagerDictLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&TObjectManager::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__TObjectManagerDict_228_0_12, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&TObjectManager::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__TObjectManagerDict_228_0_13, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&TObjectManager::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__TObjectManagerDict_228_0_14, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&TObjectManager::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__TObjectManagerDictLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__TObjectManagerDict_228_0_18, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - ClassDef_StreamerNVirtual_b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__TObjectManagerDict_228_0_19, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&TObjectManager::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__TObjectManagerDict_228_0_20, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&TObjectManager::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__TObjectManagerDict_228_0_21, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&TObjectManager::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__TObjectManagerDict_228_0_22, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&TObjectManager::DeclFileLine) ), 0);
   // automatic copy constructor
   G__memfunc_setup("TObjectManager", 1382, G__TObjectManagerDict_228_0_23, (int) ('i'), G__get_linked_tagnum(&G__TObjectManagerDictLN_TObjectManager), -1, 0, 1, 1, 1, 0, "u 'TObjectManager' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~TObjectManager", 1508, G__TObjectManagerDict_228_0_24, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__TObjectManagerDict_228_0_25, (int) ('u'), G__get_linked_tagnum(&G__TObjectManagerDictLN_TObjectManager), -1, 1, 1, 1, 1, 0, "u 'TObjectManager' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncTObjectManagerDict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {
}

static void G__cpp_setup_global2() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalTObjectManagerDict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
  G__cpp_setup_global2();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
}

static void G__cpp_setup_func14() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcTObjectManagerDict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
  G__cpp_setup_func14();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__TObjectManagerDictLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__TObjectManagerDictLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__TObjectManagerDictLN_TMemberInspector = { "TMemberInspector" , 99 , -1 };
G__linked_taginfo G__TObjectManagerDictLN_TObject = { "TObject" , 99 , -1 };
G__linked_taginfo G__TObjectManagerDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__TObjectManagerDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__TObjectManagerDictLN_TList = { "TList" , 99 , -1 };
G__linked_taginfo G__TObjectManagerDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__TObjectManagerDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__TObjectManagerDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR = { "iterator<bidirectional_iterator_tag,TObject*,long,const TObject**,const TObject*&>" , 115 , -1 };
G__linked_taginfo G__TObjectManagerDictLN_TVectorTlEfloatgR = { "TVectorT<float>" , 99 , -1 };
G__linked_taginfo G__TObjectManagerDictLN_TVectorTlEdoublegR = { "TVectorT<double>" , 99 , -1 };
G__linked_taginfo G__TObjectManagerDictLN_TObjectManager = { "TObjectManager" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableTObjectManagerDict() {
  G__TObjectManagerDictLN_TClass.tagnum = -1 ;
  G__TObjectManagerDictLN_TBuffer.tagnum = -1 ;
  G__TObjectManagerDictLN_TMemberInspector.tagnum = -1 ;
  G__TObjectManagerDictLN_TObject.tagnum = -1 ;
  G__TObjectManagerDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__TObjectManagerDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__TObjectManagerDictLN_TList.tagnum = -1 ;
  G__TObjectManagerDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__TObjectManagerDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__TObjectManagerDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR.tagnum = -1 ;
  G__TObjectManagerDictLN_TVectorTlEfloatgR.tagnum = -1 ;
  G__TObjectManagerDictLN_TVectorTlEdoublegR.tagnum = -1 ;
  G__TObjectManagerDictLN_TObjectManager.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableTObjectManagerDict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__TObjectManagerDictLN_TClass);
   G__get_linked_tagnum_fwd(&G__TObjectManagerDictLN_TBuffer);
   G__get_linked_tagnum_fwd(&G__TObjectManagerDictLN_TMemberInspector);
   G__get_linked_tagnum_fwd(&G__TObjectManagerDictLN_TObject);
   G__get_linked_tagnum_fwd(&G__TObjectManagerDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__TObjectManagerDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__TObjectManagerDictLN_TList);
   G__get_linked_tagnum_fwd(&G__TObjectManagerDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__TObjectManagerDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__TObjectManagerDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR);
   G__get_linked_tagnum_fwd(&G__TObjectManagerDictLN_TVectorTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__TObjectManagerDictLN_TVectorTlEdoublegR);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__TObjectManagerDictLN_TObjectManager),sizeof(TObjectManager),-1,62720,(char*)NULL,G__setup_memvarTObjectManager,G__setup_memfuncTObjectManager);
}
extern "C" void G__cpp_setupTObjectManagerDict(void) {
  G__check_setup_version(30051515,"G__cpp_setupTObjectManagerDict()");
  G__set_cpp_environmentTObjectManagerDict();
  G__cpp_setup_tagtableTObjectManagerDict();

  G__cpp_setup_inheritanceTObjectManagerDict();

  G__cpp_setup_typetableTObjectManagerDict();

  G__cpp_setup_memvarTObjectManagerDict();

  G__cpp_setup_memfuncTObjectManagerDict();
  G__cpp_setup_globalTObjectManagerDict();
  G__cpp_setup_funcTObjectManagerDict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncTObjectManagerDict();
  return;
}
class G__cpp_setup_initTObjectManagerDict {
  public:
    G__cpp_setup_initTObjectManagerDict() { G__add_setup_func("TObjectManagerDict",(G__incsetup)(&G__cpp_setupTObjectManagerDict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initTObjectManagerDict() { G__remove_setup_func("TObjectManagerDict"); }
};
G__cpp_setup_initTObjectManagerDict G__cpp_setup_initializerTObjectManagerDict;

