/********************************************************************
* TFitInfoDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error TFitInfoDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableTFitInfoDict();
extern void G__cpp_setup_inheritanceTFitInfoDict();
extern void G__cpp_setup_typetableTFitInfoDict();
extern void G__cpp_setup_memvarTFitInfoDict();
extern void G__cpp_setup_globalTFitInfoDict();
extern void G__cpp_setup_memfuncTFitInfoDict();
extern void G__cpp_setup_funcTFitInfoDict();
extern void G__set_cpp_environmentTFitInfoDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "/home/tiguser/packages/SharcCalibration/include/TFitInfo.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__TFitInfoDictLN_TClass;
extern G__linked_taginfo G__TFitInfoDictLN_TBuffer;
extern G__linked_taginfo G__TFitInfoDictLN_TMemberInspector;
extern G__linked_taginfo G__TFitInfoDictLN_TObject;
extern G__linked_taginfo G__TFitInfoDictLN_TNamed;
extern G__linked_taginfo G__TFitInfoDictLN_vectorlEfloatcOallocatorlEfloatgRsPgR;
extern G__linked_taginfo G__TFitInfoDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__TFitInfoDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TFitInfoDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__TFitInfoDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TFitInfoDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__TFitInfoDictLN_TF1;
extern G__linked_taginfo G__TFitInfoDictLN_TFitInfo;

/* STUB derived class for protected member access */
