/********************************************************************
* TSharcInputDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error TSharcInputDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableTSharcInputDict();
extern void G__cpp_setup_inheritanceTSharcInputDict();
extern void G__cpp_setup_typetableTSharcInputDict();
extern void G__cpp_setup_memvarTSharcInputDict();
extern void G__cpp_setup_globalTSharcInputDict();
extern void G__cpp_setup_memfuncTSharcInputDict();
extern void G__cpp_setup_funcTSharcInputDict();
extern void G__set_cpp_environmentTSharcInputDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "/home/tiguser/packages/SharcCalibration/include/TSharcInput.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__TSharcInputDictLN_TClass;
extern G__linked_taginfo G__TSharcInputDictLN_TBuffer;
extern G__linked_taginfo G__TSharcInputDictLN_TMemberInspector;
extern G__linked_taginfo G__TSharcInputDictLN_TObject;
extern G__linked_taginfo G__TSharcInputDictLN_TNamed;
extern G__linked_taginfo G__TSharcInputDictLN_string;
extern G__linked_taginfo G__TSharcInputDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__TSharcInputDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TSharcInputDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__TSharcInputDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TSharcInputDictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__TSharcInputDictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__TSharcInputDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__TSharcInputDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__TSharcInputDictLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__TSharcInputDictLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__TSharcInputDictLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__TSharcInputDictLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__TSharcInputDictLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__TSharcInputDictLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__TSharcInputDictLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__TSharcInputDictLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__TSharcInputDictLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__TSharcInputDictLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__TSharcInputDictLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__TSharcInputDictLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__TSharcInputDictLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__TSharcInputDictLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__TSharcInputDictLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__TSharcInputDictLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__TSharcInputDictLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__TSharcInputDictLN_TVector3;
extern G__linked_taginfo G__TSharcInputDictLN_TNucleus;
extern G__linked_taginfo G__TSharcInputDictLN_TKinematics;
extern G__linked_taginfo G__TSharcInputDictLN_TSharcInput;
extern G__linked_taginfo G__TSharcInputDictLN_vectorlEstringcOallocatorlEstringgRsPgR;
extern G__linked_taginfo G__TSharcInputDictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
