/********************************************************************
* TSharcNameDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error TSharcNameDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableTSharcNameDict();
extern void G__cpp_setup_inheritanceTSharcNameDict();
extern void G__cpp_setup_typetableTSharcNameDict();
extern void G__cpp_setup_memvarTSharcNameDict();
extern void G__cpp_setup_globalTSharcNameDict();
extern void G__cpp_setup_memfuncTSharcNameDict();
extern void G__cpp_setup_funcTSharcNameDict();
extern void G__set_cpp_environmentTSharcNameDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "/home/tiguser/packages/SharcCalibration/include/TSharcName.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__TSharcNameDictLN_TClass;
extern G__linked_taginfo G__TSharcNameDictLN_TBuffer;
extern G__linked_taginfo G__TSharcNameDictLN_TMemberInspector;
extern G__linked_taginfo G__TSharcNameDictLN_TObject;
extern G__linked_taginfo G__TSharcNameDictLN_string;
extern G__linked_taginfo G__TSharcNameDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__TSharcNameDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TSharcNameDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__TSharcNameDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TSharcNameDictLN_TSharcName;

/* STUB derived class for protected member access */
