/********************************************************************
* TFileManagerDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error TFileManagerDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableTFileManagerDict();
extern void G__cpp_setup_inheritanceTFileManagerDict();
extern void G__cpp_setup_typetableTFileManagerDict();
extern void G__cpp_setup_memvarTFileManagerDict();
extern void G__cpp_setup_globalTFileManagerDict();
extern void G__cpp_setup_memfuncTFileManagerDict();
extern void G__cpp_setup_funcTFileManagerDict();
extern void G__set_cpp_environmentTFileManagerDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "/home/bender/Programs/SharcCalibration/include/TFileManager.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__TFileManagerDictLN_TClass;
extern G__linked_taginfo G__TFileManagerDictLN_TBuffer;
extern G__linked_taginfo G__TFileManagerDictLN_TMemberInspector;
extern G__linked_taginfo G__TFileManagerDictLN_TObject;
extern G__linked_taginfo G__TFileManagerDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__TFileManagerDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TFileManagerDictLN_TList;
extern G__linked_taginfo G__TFileManagerDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__TFileManagerDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TFileManagerDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__TFileManagerDictLN_TFile;
extern G__linked_taginfo G__TFileManagerDictLN_TDirectoryFile;
extern G__linked_taginfo G__TFileManagerDictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__TFileManagerDictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__TFileManagerDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__TFileManagerDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__TFileManagerDictLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__TFileManagerDictLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__TFileManagerDictLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__TFileManagerDictLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__TFileManagerDictLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__TFileManagerDictLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__TFileManagerDictLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__TFileManagerDictLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__TFileManagerDictLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__TFileManagerDictLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__TFileManagerDictLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__TFileManagerDictLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__TFileManagerDictLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__TFileManagerDictLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__TFileManagerDictLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__TFileManagerDictLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__TFileManagerDictLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__TFileManagerDictLN_vectorlEstringcOallocatorlEstringgRsPgR;
extern G__linked_taginfo G__TFileManagerDictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TFileManagerDictLN_TFileManager;

/* STUB derived class for protected member access */
