/********************************************************************
* TCalibrateDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error TCalibrateDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableTCalibrateDict();
extern void G__cpp_setup_inheritanceTCalibrateDict();
extern void G__cpp_setup_typetableTCalibrateDict();
extern void G__cpp_setup_memvarTCalibrateDict();
extern void G__cpp_setup_globalTCalibrateDict();
extern void G__cpp_setup_memfuncTCalibrateDict();
extern void G__cpp_setup_funcTCalibrateDict();
extern void G__set_cpp_environmentTCalibrateDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "/home/bender/Programs/SharcCalibration/include/TCalibrate.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__TCalibrateDictLN_TClass;
extern G__linked_taginfo G__TCalibrateDictLN_TBuffer;
extern G__linked_taginfo G__TCalibrateDictLN_TMemberInspector;
extern G__linked_taginfo G__TCalibrateDictLN_TObject;
extern G__linked_taginfo G__TCalibrateDictLN_TNamed;
extern G__linked_taginfo G__TCalibrateDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__TCalibrateDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TCalibrateDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__TCalibrateDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TCalibrateDictLN_TCalibrate;
extern G__linked_taginfo G__TCalibrateDictLN_maplEstringcOboolcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOboolgRsPgRsPgR;

/* STUB derived class for protected member access */
