/********************************************************************
* TFitManagerDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error TFitManagerDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableTFitManagerDict();
extern void G__cpp_setup_inheritanceTFitManagerDict();
extern void G__cpp_setup_typetableTFitManagerDict();
extern void G__cpp_setup_memvarTFitManagerDict();
extern void G__cpp_setup_globalTFitManagerDict();
extern void G__cpp_setup_memfuncTFitManagerDict();
extern void G__cpp_setup_funcTFitManagerDict();
extern void G__set_cpp_environmentTFitManagerDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "/home/tiguser/packages/SharcCalibration/include/TFitManager.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__TFitManagerDictLN_TClass;
extern G__linked_taginfo G__TFitManagerDictLN_TBuffer;
extern G__linked_taginfo G__TFitManagerDictLN_TMemberInspector;
extern G__linked_taginfo G__TFitManagerDictLN_TObject;
extern G__linked_taginfo G__TFitManagerDictLN_TNamed;
extern G__linked_taginfo G__TFitManagerDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR;
extern G__linked_taginfo G__TFitManagerDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__TFitManagerDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TFitManagerDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__TFitManagerDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TFitManagerDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__TFitManagerDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__TFitManagerDictLN_TH1D;
extern G__linked_taginfo G__TFitManagerDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__TFitManagerDictLN_TGraph;
extern G__linked_taginfo G__TFitManagerDictLN_TSpectrum;
extern G__linked_taginfo G__TFitManagerDictLN_TFitInfo;
extern G__linked_taginfo G__TFitManagerDictLN_TFitManager;
extern G__linked_taginfo G__TFitManagerDictLN_vectorlEstringcOallocatorlEstringgRsPgR;
extern G__linked_taginfo G__TFitManagerDictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
