/********************************************************************
* TFitManagerDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error TFitManagerDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableTFitManagerDict();
extern void G__cpp_setup_inheritanceTFitManagerDict();
extern void G__cpp_setup_typetableTFitManagerDict();
extern void G__cpp_setup_memvarTFitManagerDict();
extern void G__cpp_setup_globalTFitManagerDict();
extern void G__cpp_setup_memfuncTFitManagerDict();
extern void G__cpp_setup_funcTFitManagerDict();
extern void G__set_cpp_environmentTFitManagerDict();
}


#include "TObject.h"
