/********************************************************************
* TSharcFormatDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error TSharcFormatDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableTSharcFormatDict();
extern void G__cpp_setup_inheritanceTSharcFormatDict();
extern void G__cpp_setup_typetableTSharcFormatDict();
extern void G__cpp_setup_memvarTSharcFormatDict();
extern void G__cpp_setup_globalTSharcFormatDict();
extern void G__cpp_setup_memfuncTSharcFormatDict();
extern void G__cpp_setup_funcTSharcFormatDict();
extern void G__set_cpp_environmentTSharcFormatDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "/home/bender/Programs/SharcCalibration/include/TSharcFormat.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__TSharcFormatDictLN_TClass;
extern G__linked_taginfo G__TSharcFormatDictLN_TBuffer;
extern G__linked_taginfo G__TSharcFormatDictLN_TMemberInspector;
extern G__linked_taginfo G__TSharcFormatDictLN_TObject;
extern G__linked_taginfo G__TSharcFormatDictLN_string;
extern G__linked_taginfo G__TSharcFormatDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__TSharcFormatDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TSharcFormatDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__TSharcFormatDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TSharcFormatDictLN_TSharcFormat;

/* STUB derived class for protected member access */
