/********************************************************************
* TFileWriterDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error TFileWriterDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableTFileWriterDict();
extern void G__cpp_setup_inheritanceTFileWriterDict();
extern void G__cpp_setup_typetableTFileWriterDict();
extern void G__cpp_setup_memvarTFileWriterDict();
extern void G__cpp_setup_globalTFileWriterDict();
extern void G__cpp_setup_memfuncTFileWriterDict();
extern void G__cpp_setup_funcTFileWriterDict();
extern void G__set_cpp_environmentTFileWriterDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "/home/tiguser/packages/SharcCalibration/include/TFileWriter.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__TFileWriterDictLN_TClass;
extern G__linked_taginfo G__TFileWriterDictLN_TBuffer;
extern G__linked_taginfo G__TFileWriterDictLN_TMemberInspector;
extern G__linked_taginfo G__TFileWriterDictLN_TObject;
extern G__linked_taginfo G__TFileWriterDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__TFileWriterDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TFileWriterDictLN_TList;
extern G__linked_taginfo G__TFileWriterDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__TFileWriterDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TFileWriterDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__TFileWriterDictLN_TFile;
extern G__linked_taginfo G__TFileWriterDictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__TFileWriterDictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__TFileWriterDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__TFileWriterDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__TFileWriterDictLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__TFileWriterDictLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__TFileWriterDictLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__TFileWriterDictLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__TFileWriterDictLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__TFileWriterDictLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__TFileWriterDictLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__TFileWriterDictLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__TFileWriterDictLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__TFileWriterDictLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__TFileWriterDictLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__TFileWriterDictLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__TFileWriterDictLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__TFileWriterDictLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__TFileWriterDictLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__TFileWriterDictLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__TFileWriterDictLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__TFileWriterDictLN_TFileWriter;

/* STUB derived class for protected member access */
