/********************************************************************
* TDataManagerDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error TDataManagerDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableTDataManagerDict();
extern void G__cpp_setup_inheritanceTDataManagerDict();
extern void G__cpp_setup_typetableTDataManagerDict();
extern void G__cpp_setup_memvarTDataManagerDict();
extern void G__cpp_setup_globalTDataManagerDict();
extern void G__cpp_setup_memfuncTDataManagerDict();
extern void G__cpp_setup_funcTDataManagerDict();
extern void G__set_cpp_environmentTDataManagerDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "/home/tiguser/packages/SharcCalibration/include/TDataManager.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__TDataManagerDictLN_TClass;
extern G__linked_taginfo G__TDataManagerDictLN_TBuffer;
extern G__linked_taginfo G__TDataManagerDictLN_TMemberInspector;
extern G__linked_taginfo G__TDataManagerDictLN_TObject;
extern G__linked_taginfo G__TDataManagerDictLN_TNamed;
extern G__linked_taginfo G__TDataManagerDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__TDataManagerDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TDataManagerDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__TDataManagerDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TDataManagerDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__TDataManagerDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__TDataManagerDictLN_TChain;
extern G__linked_taginfo G__TDataManagerDictLN_TSharc;
extern G__linked_taginfo G__TDataManagerDictLN_TTigress;
extern G__linked_taginfo G__TDataManagerDictLN_TTriFoil;
extern G__linked_taginfo G__TDataManagerDictLN_TSharcHit;
extern G__linked_taginfo G__TDataManagerDictLN_TTigressHit;
extern G__linked_taginfo G__TDataManagerDictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__TDataManagerDictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__TDataManagerDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__TDataManagerDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__TDataManagerDictLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__TDataManagerDictLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__TDataManagerDictLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__TDataManagerDictLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__TDataManagerDictLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__TDataManagerDictLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__TDataManagerDictLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__TDataManagerDictLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__TDataManagerDictLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__TDataManagerDictLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__TDataManagerDictLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__TDataManagerDictLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__TDataManagerDictLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__TDataManagerDictLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__TDataManagerDictLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__TDataManagerDictLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__TDataManagerDictLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__TDataManagerDictLN_vectorlEstringcOallocatorlEstringgRsPgR;
extern G__linked_taginfo G__TDataManagerDictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TDataManagerDictLN_TDataManager;

/* STUB derived class for protected member access */
